version: '3'
services:
  postgres:
    image: postgres:10-alpine
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
    - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    - "./pgconfig:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "fengshuaiju"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka-broker:
    image: wurstmeister/kafka:2.12-2.4.0
    hostname: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: kafka-broker
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  connector:
    image: connector
    hostname: connector
    restart: on-failure
    ports:
      - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_config
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_status
      BOOTSTRAP_SERVERS: kafka-broker:9092
    depends_on:
      - kafka-broker
      - postgres
